version: '3'

services:
  marketplace:
    restart: always
    image: marketplace
    environment:
      - VENDOR=xtraball
    volumes:
      - ./service:/var/www/html
    build:
      context: .
      dockerfile: ./marketplace/Dockerfile
    entrypoint: /home/backup/wrapper.sh
    networks:
      - marketplace-bridge

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./service:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - marketplace-bridge

networks:
  marketplace-bridge:
    driver: bridge
